name: Pipeline

on: [push]

jobs:
  build:
    name: "Test"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true

    steps:
      - uses: actions/checkout@v3

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.3.1

      - name: Cache Batect
        uses: actions/cache@v3
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Test sample setup
        run: ./batect test
